drop type if exists grocery;

create type grocery as enum(
  'Main',
  'Lunch',
  'Snack',
  'Breakfast'
);

create table if not exists shopping_list (
  id integer primary key generated by default as identity,
  name text not null,
  price numeric,
  category grocery,
  checked BOOLEAN DEFAULT false,
  date_added TIMESTAMP DEFAULT now() NOT NULL
);

